# Makefile
LDFLAGS=-lncurses
SRC = ft_attr_players.c
OBJ = ft_attr_players.o
all: corewargraphicdemo
corewargraphicdemo: $(SRC)

fclean:
	rm -rf $(OBJ)
	rm -rf corewargraphicdemo.o
	rm -rf corewargraphicdemo